SSBU_Stage_Guide/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('guide.urls')),
]

guide/urls.py
from django.urls import path

from . import views

app_name = 'guide'
urlpatterns = [
    #path('', views.index, name='index'),
    path('', views.HomepageView.as_view(), name='homepage'),
    path('contact', views.ContactView.as_view(), name='contact'),
    path('about', views.AboutView.as_view(), name='about'),
    path('matchups', views.MatchupsView.as_view(), name='matchups'),
    path('matchupsearch', views.MatchupSearchView, name='matchupsearch'),
    path('matchups/<str:pk>/<str:opponentChar>', views.MatchupInfoView.as_view(), name='matchupinfo'),
    path('search', views.SearchView, name='search'),
    path('<str:pk>/', views.CharacterView.as_view(), name='character'),
    path('<str:charactername>/vote/', views.VoteView.as_view(), name='vote'),
    path('<str:charactername>/revote/', views.RevoteView.as_view(), name='revote'),
    path('privacypolicy', views.PrivacyView.as_view(), name='privacy'),
    path('termsandconditions', views.TermsView.as_view(), name='terms'),
    path('cookiepolicy', views.CookieView.as_view(), name='cookie'),
]

guide/models.py
from django.db import models
import urllib.parse

# Create your models here.

class Character(models.Model):
    name = models.CharField(max_length=30, primary_key=True)
    number = models.IntegerField()
    image = models.CharField(max_length=30)
    link = models.CharField(max_length=150, null=True)

    def __str__(self):
        """
        String representation is the character name.
        """
        return self.name

    def quoted_name(self):
        """
        Returns the url safe version of character name.
        Django autoescapes html so seemingly pointless.
        """
        return urllib.parse.quote(self.name, safe='')

    def image_link(self):
        """
        Returns the path to the image of the character.
        """
        return 'guide/images/' + self.image

class Vote(models.Model):
    # session key of user
    sessionid = models.CharField(max_length=32, blank=True, null=True)
    # date/time submitted
    timestampUpdated = models.DateTimeField('Updated', auto_now=True)
    timestampCreated = models.DateTimeField('Created', auto_now_add=True)
    # name of character is foreign key
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    # the name of stage represents the vote value
    battlefield = models.SmallIntegerField(blank=True, null=True)
    final_destination = models.SmallIntegerField(blank=True, null=True)
    pokemon_stadium = models.SmallIntegerField(blank=True, null=True)
    small_battlefield = models.SmallIntegerField(blank=True, null=True) # added 10/1/20
    smashville = models.SmallIntegerField(blank=True, null=True)
    town = models.SmallIntegerField(blank=True, null=True)
    lylat = models.SmallIntegerField(blank=True, null=True)
    kalos = models.SmallIntegerField(blank=True, null=True)
    yoshi_story = models.SmallIntegerField(blank=True, null=True)
    yoshi_island = models.SmallIntegerField(blank=True, null=True)
    unova = models.SmallIntegerField(blank=True, null=True)

    def __str__(self):
        """
        String representation is the character name.
        """
        return (str(self.character) + str(self.battlefield) +  str(self.small_battlefield) + str(self.final_destination) + str(self.pokemon_stadium) +
                str(self.smashville) + str(self.town) + str(self.lylat) + str(self.kalos) + str(self.yoshi_story) + 
                str(self.yoshi_island) + str(self.unova) )

guide/views.py
from django.shortcuts import get_object_or_404, render
import uuid

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.template import loader
from django.views import generic
from django import forms

import urllib.parse
from django.db.models import Avg
import math

from .models import Character, Vote

# the homepage
"""
class HomepageView(generic.ListView):
    template_name = 'guide/homepage.html'
    context_object_name = 'character_list'

    def get_queryset(self):
        #Return all characters ordered alphabetically.
        return Character.objects.order_by('name')
"""

class HomepageView(generic.TemplateView):
    template_name = 'guide/homepagetemplate.html'

class PrivacyView(generic.TemplateView):
    template_name = 'guide/privacypolicy.html'

class CookieView(generic.TemplateView):
    template_name = 'guide/cookiepolicy.html'

class TermsView(generic.TemplateView):
    template_name = 'guide/termsconditions.html'


# helper function for CharacterView to map variable names to readable names
def varToName(d, votes):
    mappedDict = []
    for key, value in d.items():
        img = ''
        # map to readable names
        if key == 'battlefield__avg':
            key = 'Battlefield'
            img = 'guide/stage_images/' + 'battlefield.png'
            #img = "https://www.ssbwiki.com/images/thumb/8/86/SSBU-Battlefield.png/300px-SSBU-Battlefield.png"
            numVotes = votes.filter(battlefield__isnull=False).count()
        elif key == 'final_destination__avg':
            key = 'Final Destination'
            img = 'guide/stage_images/' + 'final_destination.jpg'
            #img = "https://www.ssbwiki.com/images/thumb/9/91/SSBU-Final_Destination.jpg/300px-SSBU-Final_Destination.jpg"
            numVotes = votes.filter(final_destination__isnull=False).count()
        elif key == 'pokemon_stadium__avg':
            key = 'Pokémon Stadium 2'
            img = 'guide/stage_images/' + 'pokemon_stadium.png'
            #img = "https://www.ssbwiki.com/images/thumb/7/73/SSBU-Pok%C3%A9mon_Stadium_2.png/300px-SSBU-Pok%C3%A9mon_Stadium_2.png"
            numVotes = votes.filter(pokemon_stadium__isnull=False).count()
        elif key == 'small_battlefield__avg':
            key = 'Small Battlefield'
            img = 'guide/stage_images/' + 'small_battlefield.jpg'
            #img = "https://www.ssbwiki.com/images/thumb/7/7e/SSBU-Small-Battlefield.jpg/300px-SSBU-Small-Battlefield.jpg"
            numVotes = votes.filter(small_battlefield__isnull=False).count()
        elif key == 'smashville__avg':
            key = 'Smashville'
            img = 'guide/stage_images/' + 'smashville.png'
            #img = "https://www.ssbwiki.com/images/thumb/0/02/SSBU-Smashville.png/300px-SSBU-Smashville.png"
            numVotes = votes.filter(smashville__isnull=False).count()
        elif key == 'lylat__avg':
            key = 'Lylat Cruise'
            img = 'guide/stage_images/' + 'lylat.jpg'
            #img = "https://www.ssbwiki.com/images/thumb/5/5f/SSBU-Lylat_Cruise.jpg/300px-SSBU-Lylat_Cruise.jpg"
            numVotes = votes.filter(lylat__isnull=False).count()
        elif key == 'town__avg':
            key = 'Town and City'
            img = 'guide/stage_images/' + 'town.png'
            #img = "https://www.ssbwiki.com/images/thumb/2/26/SSBU-Town_and_City.png/300px-SSBU-Town_and_City.png"
            numVotes = votes.filter(town__isnull=False).count()
        elif key == 'kalos__avg':
            key = 'Kalos'
            img = 'guide/stage_images/' + 'kalos.png'
            #img = "https://www.ssbwiki.com/images/thumb/b/bf/SSBU-Kalos_Pok%C3%A9mon_League.png/300px-SSBU-Kalos_Pok%C3%A9mon_League.png"
            numVotes = votes.filter(kalos__isnull=False).count()
        elif key == 'yoshi_story__avg':
            key = "Yoshi's Story"
            img = 'guide/stage_images/' + 'yoshi_story.png'
            #img = "https://www.ssbwiki.com/images/thumb/0/0c/SSBU-Yoshi%27s_Story.png/300px-SSBU-Yoshi%27s_Story.png"
            numVotes = votes.filter(yoshi_story__isnull=False).count()
        elif key == 'yoshi_island__avg':
            key = "Yoshi's Island"
            img = 'guide/stage_images/' + 'yoshi_island.png'
            #img = "https://www.ssbwiki.com/images/thumb/7/7b/SSBU-Yoshi%27s_Island_%28SSBB%29.png/300px-SSBU-Yoshi%27s_Island_%28SSBB%29.png"
            numVotes = votes.filter(yoshi_island__isnull=False).count()
        elif key == 'unova__avg':
            key = "Unova"
            img = 'guide/stage_images/' + 'unova.png'
            #img = "https://www.ssbwiki.com/images/thumb/b/b2/SSBU-Unova_Pok%C3%A9mon_League.png/300px-SSBU-Unova_Pok%C3%A9mon_League.png"
            numVotes = votes.filter(unova__isnull=False).count()
        temp = [key, value, img, numVotes]
        mappedDict.append(temp)
    return mappedDict

# displays stage rankings for a character
class CharacterView(generic.DetailView):
    model = Character
    template_name = 'guide/character.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Check cookies to see whether user voted on character or not
        if str(context['character']) in self.request.session and self.request.session[str(context['character'])] == True:
            context['voted_already'] = True
        else:
            context['voted_already'] = False
        #for key, value in self.request.session.items():
        #    print('{} => {}'.format(key, value))
        # Process the votes into a list then add to context
        character = context['character']
        votes = character.vote_set.all()
        
        # if no votes, empty list
        if not votes:
            context['votes'] = []
            context['num_votes'] = 0
        # otherwise get average score and order list
        else:
            # get average score of each stage
            vote_avgs_dict = votes.aggregate(Avg('battlefield'), Avg('final_destination'), Avg('pokemon_stadium'), Avg('small_battlefield'),
                Avg('smashville'), Avg('town'), Avg('lylat'), Avg('kalos'), Avg('yoshi_story'), 
                Avg('yoshi_island'), Avg('unova'))

            # convert to list of form (stage_name, score)
            vote_avgs = varToName(vote_avgs_dict, votes)

            

            # sort stage by avg score
            #vote_avgs.sort(key = lambda x: x[1], reverse=True)
            vote_avgs.sort(key = lambda x: -1 * math.inf if x[1] is None else x[1], reverse=True)

            # considered changing Nones to 0s, changed mind
            """
            # convert Nones to 0's
            for x in vote_avgs:
                if x[1] is None:
                    x[1] = 0
            """

            
            # set context
            context['votes'] = vote_avgs
            context['num_votes'] = len(votes)
        return context

# static page - contact information
class ContactView(generic.TemplateView):
    template_name = 'guide/contact.html'

# static page - info about the site
class AboutView(generic.TemplateView):
    template_name = 'guide/about.html'

# search page/form for matchups
class MatchupsView(generic.TemplateView):
    template_name = 'guide/matchups.html'

class VoteModelForm(forms.ModelForm):
    VOTEVALUES=[
         (3, '3: Best'),
         (2, '2: Great'),
         (1, '1: Good'),
         (0, '0: Neutral'),
         (-1, '-1: Bad'),
         (-2, '-2: Terrible'),
         (-3, '-3: Worst'),
         ('', 'N/A')
         ]
    
    battlefield = forms.ChoiceField(label='Battlefield', choices=VOTEVALUES, widget=forms.RadioSelect, required=False)
    final_destination = forms.ChoiceField(label='Final Destination', choices=VOTEVALUES, widget=forms.RadioSelect, required=False)
    pokemon_stadium = forms.ChoiceField(label='Pokémon Stadium 2', choices=VOTEVALUES, widget=forms.RadioSelect, required=False)
    small_battlefield = forms.ChoiceField(label='Small Battlefield', choices=VOTEVALUES, widget=forms.RadioSelect, required=False)
    smashville = forms.ChoiceField(label='Smashville', choices=VOTEVALUES, widget=forms.RadioSelect, required=False)
    town = forms.ChoiceField(label='Town and City', choices=VOTEVALUES, widget=forms.RadioSelect, required=False)
    lylat = forms.ChoiceField(label='Lylat Cruise', choices=VOTEVALUES, widget=forms.RadioSelect, required=False)
    kalos = forms.ChoiceField(label='Kalos', choices=VOTEVALUES, widget=forms.RadioSelect, required=False)
    yoshi_story = forms.ChoiceField(label="Yoshi's Story", choices=VOTEVALUES, widget=forms.RadioSelect, required=False)
    yoshi_island = forms.ChoiceField(label="Yoshi's Island", choices=VOTEVALUES, widget=forms.RadioSelect, required=False)
    unova = forms.ChoiceField(label='Unova', choices=VOTEVALUES, widget=forms.RadioSelect, required=False)
    sessionid = forms.CharField(label='sessionid', widget=forms.HiddenInput)
    

    # make sure scores are between -2 and 2, and that blank strings convert to None
    def clean_battlefield(self):
        battlefield = self.cleaned_data['battlefield']
        if not battlefield:
            battlefield = None
        elif int(battlefield) > 3 or int(battlefield) < -3:
            raise forms.ValidationError("Only scores between -3 and 3 allowed.")
        return battlefield

    def clean_final_destination(self):
        final_destination = self.cleaned_data['final_destination']
        if not final_destination:
            final_destination = None
        elif int(final_destination) > 3 or int(final_destination) < -3:
            raise forms.ValidationError("Only scores between -3 and 3 allowed.")
        return final_destination
    
    def clean_pokemon_stadium(self):
        pokemon_stadium = self.cleaned_data['pokemon_stadium']
        if not pokemon_stadium:
            pokemon_stadium = None

guide/templates/guide/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- own stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'guide/style.css' %}">

    <!-- Latest compiled and minified CSS for bootstrap-select -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">


    <!-- Cookie banner -->
    <link rel="stylesheet" type="text/css" href="https://cdn.wpcc.io/lib/1.0.2/cookieconsent.min.css"/><script src="https://cdn.wpcc.io/lib/1.0.2/cookieconsent.min.js"></script><script>window.addEventListener("load", function(){window.wpcc.init({"border":"thin","corners":"small","colors":{"popup":{"background":"#fff0ca","text":"#000000","border":"#e0bc57"},"button":{"background":"#e0bc57","text":"#ffffff"}},"position":"bottom-right","content":{"href":"{% url 'guide:cookie' %}"}})});</script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-170900949-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-170900949-2');
    </script>


    {% block metadata %}
    
    {% endblock %}
  </head>
  <body>
    <!-- Navbar at top of every page -->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffa500;">
        <a class="navbar-brand" href="{% url 'guide:homepage' %}" style=" font-weight: bold;">SSBU Stage Guides</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'guide:homepage' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'guide:matchups' %}">Matchups</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'guide:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'guide:contact' %}">Contact</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" action="{% url 'guide:search' %}" method="get">
            <select class="selectpicker" data-live-search="true" data-live-search-style="startsWith" id="Character" name="Character" title="Search character name..." required>
              <option value="Banjo & Kazooie">Banjo & Kazooie</option>
              <option value="Bayonetta">Bayonetta</option>
              <option value="Bowser">Bowser</option>
              <option value="Bowser Jr." data-tokens="Jr.">Bowser Jr.</option>
              <option value="Byleth">Byleth</option>
              <option value="Captain Falcon">Captain Falcon</option>
              <option value="Charizard">Charizard</option>
              <option value="Chrom">Chrom</option>
              <option value="Cloud">Cloud</option>
              <option value="Corrin">Corrin</option>
              <option value="Dark Pit">Dark Pit</option>
              <option value="Diddy Kong">Diddy Kong</option>
              <option value="Donkey Kong">Donkey Kong</option>
              <option value="Dr. Mario" data-tokens="Doctor">Dr. Mario</option>
              <option value="Duck Hunt">Duck Hunt</option>
              <option value="Falco">Falco</option>
              <option value="Fox">Fox</option>
              <option value="Ganondorf">Ganondorf</option>
              <option value="Greninja">Greninja</option>
              <option value="Hero">Hero</option>
              <option value="Ice Climbers" data-tokens="Climbers">Ice Climbers</option>
              <option value="Ike">Ike</option>
              <option value="Incineroar">Incineroar</option>
              <option value="Inkling">Inkling</option>
              <option value="Isabelle">Isabelle</option>
              <option value="Ivysaur">Ivysaur</option>
              <option value="Jigglypuff">Jigglypuff</option>
              <option value="Joker">Joker</option>
              <option value="Kazuya">Kazuya</option>
              <option value="Ken">Ken</option>
              <option value="King Dedede" data-tokens="Dedede">King Dedede</option>
              <option value="King K. Rool" data-tokens="K Rool">King K. Rool</option>
              <option value="Kirby">Kirby</option>
              <option value="Link">Link</option>
              <option value="Little Mac">Little Mac</option>
              <option value="Lucario">Lucario</option>
              <option value="Lucas">Lucas</option>
              <option value="Luigi">Luigi</option>
              <option value="Mario">Mario</option>
              <option value="Marth (Lucina)" data-tokens="Lucina">Marth (Lucina)</option>
              <option value="Mega Man">Mega Man</option>
              <option value="Meta Knight">Meta Knight</option>
              <option value="Mewtwo">Mewtwo</option>
              <option value="Mii Brawler" data-tokens="Brawler">Mii Brawler</option>
              <option value="Mii Gunner" data-tokens="Gunner">Mii Gunner</option>
              <option value="Mii Swordfighter" data-tokens="Swordfighter">Mii Swordfighter</option>
              <option value="Min Min">Min Min</option>
              <option value="Mr. Game & Watch" data-tokens="Game & Watch">Mr. Game & Watch</option>
              <option value="Ness">Ness</option>
              <option value="Olimar">Olimar</option>
              <option value="Pac-Man">Pac-Man</option>
              <option value="Palutena">Palutena</option>
              <option value="Peach (Daisy)" data-tokens="Daisy">Peach (Daisy)</option>
              <option value="Pichu">Pichu</option>
              <option value="Pikachu">Pikachu</option>
              <option value="Piranha Plant" data-tokens="Plant">Piranha Plant</option>
              <option value="Pit">Pit</option>
              <option value="Pokémon Trainer" data-tokens="Pokemon Trainer">Pokémon Trainer</option>
              <option value="Pyra & Mythra" data-tokens="Mythra">Pyra & Mythra</option>
              <option value="Ridley">Ridley</option>
              <option value="R.O.B." data-tokens="ROB">R.O.B.</option>
              <option value="Robin">Robin</option>
              <option value="Rosalina & Luma">Rosalina & Luma</option>
              <option value="Roy">Roy</option>
              <option value="Ryu">Ryu</option>
              <option value="Samus (Dark Samus)" data-tokens="Dark Samus">Samus (Dark Samus)</option>
              <option value="Sephiroth">Sephiroth</option>
              <option value="Sheik">Sheik</option>
              <option value="Shulk">Shulk</option>
              <option value="Simon (Richter)" data-tokens="Richter">Simon (Richter)</option>
              <option value="Snake">Snake</option>
              <option value="Sonic">Sonic</option>
              <option value="Sora">Sora</option>
              <option value="Squirtle">Squirtle</option>
              <option value="Steve">Steve</option>
              <option value="Terry">Terry</option>
              <option value="Toon Link">Toon Link</option>
              <option value="Villager">Villager</option>
              <option value="Wario">Wario</option>
              <option value="Wii Fit Trainer">Wii Fit Trainer</option>
              <option value="Wolf">Wolf</option>
              <option value="Yoshi">Yoshi</option>
              <option value="Young Link">Young Link</option>
              <option value="Zelda">Zelda</option>
              <option value="Zero Suit Samus">Zero Suit Samus</option>
            </select>
            &nbsp;
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
    </nav>

    {% block content %}
    
    {% endblock %}

    <!-- Footer at bottom of every page -->
    <div class="jumbotron text-center" style="margin-bottom:0">
        <p>SSBU Stage Guides isn't endorsed by Nintendo and doesn't reflect the views or opinions of Nintendo or anyone officially involved in producing or managing Super Smash Bros. <br>
          Super Smash Bros. and Nintendo are trademarks or registered trademarks of Nintendo CO., LTD</p>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified JavaScript for bootstrap-select -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <!-- (Optional) Latest compiled and minified JavaScript translation files for bootstrap-select -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/i18n/defaults-*.min.js"></script>
  </body>
</html>

guide/templates/guide/character.html
{% extends "guide/base.html" %}
{% load static %}

{% block content %}

<div class="text-center">
<h1 style="font-weight: bold;">{{ character.name }}</h1>
</div>

<div class="text-center">
<img src="{{ character.link }}" class="img-fluid" alt="character art" style="height:250px;">
</div>

<div class="text-center">
    {% if voted_already %}
    Thanks for voting!<br>
    <a href="{% url 'guide:revote' character.name %}" class="btn btn-primary">Revote on Stages</a>
    {% else %}
    <a href="{% url 'guide:vote' character.name %}" class="btn btn-primary">Vote on Stages</a>
    {% endif %}

</div>

{% if votes %}
    <p class="text-center">Total votes: {{ num_votes }}</p>
    <!-- for debugging
    <p>{{votes}}</p>
     -->
    <h2 class="text-center" style="font-weight: bold; font-size: 35px;">Stage Rankings</h2>
    <div class="container-fluid">
        <div class="row">
            {% for vote in votes %} 
                <div class="col-6 col-md-3">
                    <h4>
                        <b>#{{forloop.counter}}: {{vote.0}} </b><br>
                        <img id="{{forloop.counter}}" src="{% static vote.2 %}" alt="stage image" class="rounded border border-dark" style="border-width:2px !important;" onclick="greyOutFxn{{forloop.counter}}()" width="150" height="84">
                        <script>
                            function greyOutFxn{{forloop.counter}}(){
                                var stage = document.getElementById('{{forloop.counter}}');
                                if (stage.style.filter != "grayscale(100%)") {
                                    stage.style.filter = "grayscale(100%)";
                                    //stage.style.className = "rounded border border-danger";
                                }
                                else{
                                    stage.style.filter = "none";
                                    //stage.style.className = "rounded border border-secondary";
                                }
                            }
                        </script>
                        <br>
                        Score: {{vote.1|floatformat:2}} {% if vote.1 is None %} No votes. {% endif %} <br>
                        ({{vote.3}} votes)
                    </h4>
                </div>
            {% endfor %}
        </div>
    </div>

{% else %}
<p class="text-center">There are no votes yet. <br> Please contribute if you can!</p>
{% endif %}

<br><br>

<!-- begin wwww.htmlcommentbox.com -->
<div id="HCB_comment_box"><a href="http://www.htmlcommentbox.com">HTML Comment Box</a> is loading comments...</div>
<link rel="stylesheet" type="text/css" href="https://www.htmlcommentbox.com/static/skins/bootstrap/twitter-bootstrap.css?v=0" />
<script type="text/javascript" id="hcb"> /*<!--*/ if(!window.hcb_user){hcb_user={};} (function(){var s=document.createElement("script"), l=hcb_user.PAGE || (""+window.location).replace(/'/g,"%27"), h="https://www.htmlcommentbox.com";s.setAttribute("type","text/javascript");s.setAttribute("src", h+"/jread?page="+encodeURIComponent(l).replace("+","%2B")+"&mod=%241%24wq1rdBcg%24dFIEN7Ub0828fq.xRLQAC."+"&opts=16862&num=10&ts=1592607004055");if (typeof s!="undefined") document.getElementsByTagName("head")[0].appendChild(s);})(); /*-->*/ </script>
<!-- end www.htmlcommentbox.com -->

{% endblock %}

{% block metadata %}
<title>{{character.name}}</title>
<meta name="description" content="Stage rankings and advice for {{character.name}}">
<meta name="keywords" content="Super Smash Bros. Ultimate, Super Smash Bros. Ultimate stage advice, {{character.name}}, {{character.name}} stage rankings, {{character.name}} best stages, {{character.name}} stages, ssbu, ssbu stage guides, smash ultimate stage guides, Smash Bros. Ultimate stage guides, Smash Bros. Ultimate stage guide, Super Smash Bros. Ultimate matchup, stage rankings, smash ultimate, smash ultimate stages, best stages against, stage bans, worst stages against, stage ban, competitive smash, best stages, worst stages">
<meta name="robots" content="index, follow">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="language" content="English">
{% endblock %}

guide/templates/guide/homepage_old.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'guide/style.css' %}">

{% if character_list %}
    <ul>
    {% for character in character_list %}
        <li>{{ character.name }}</a></li>
        <a href="{% url 'guide:character' character.name %}">
        <img src="{% static character.image_link %}" alt="character">
        </a>
    {% endfor %}
    </ul>
{% else %}
    <p>No characters at this time.</p>
{% endif %}